### ISSUE TITLE
Minor Quest Issue: v1.2.2 Market > Weapons > Thin Handled Iron Scythe (Named 7x Trader Token)

### ISSUE THREAD

**Issue by MFnTruth** [NFINIT-Labs/Fantasy-Skies#14]
After opening the Weapon quest-line every time there is 7 tokens in the player's inventory it completes the Thin Handled Iron Scythe quest (giving the player a free Scythe every time)

**Comment by knoxhack** [comment]
Fixed in 1.3.x
