### ISSUE TITLE
Warden Tendril is not on Warden loot table v 1.2.0 and 1.2.2

### ISSUE THREAD

**Issue by meglazero** [NFINIT-Labs/Fantasy-Skies#19]
There is no method in game according to JEI to obtain the Warden Tendril as of now, I have killed several Wardens on both 1.2.0 and 1.2.2 and not received any. This heavily gates enchanting since you are stuck at 37.5 eterna at maximum without a warden tendril or getting insanely lucky with an ancient affix item to get 2 ancient materials out of to push you over 40 eterna for the end shelves.

**Comment by knoxhack** [comment]
temp recipe added in 1.3.2
