### ISSUE TITLE
Primal Magick Dissolution Chamber research not completable

### ISSUE THREAD

**Issue by meglazero** [NFINIT-Labs/Fantasy-Skies#26]
The research recipe calls for iron, copper and gold grit, which are classified as forge dusts so almostunified is removing them from the crafting table for earthshatter hammer within the mod.

An easy fix is to just update the unify.json config for almostunified to:

`  "ignoredItems": ["primalmagick:iron_grit","primalmagick:copper_grit","primalmagick:gold_grit"],`

**Comment by knoxhack** [comment]
Implemented in 1.4.0
