### ISSUE TITLE
Pistons cause a game crash in 1.3.2

### ISSUE THREAD

**Issue by lethalitycomplex** [NFINIT-Labs/Fantasy-Skies#27]
As the title says; using pistons, either regular or sticky, in 1.3.2 seems to crash the game due to an error in the mixin chain. I'm not exactly sure what's causing it, but attached are some crashlogs for reference. I tried updating to the latest Forge patch as well (as you'll see in the later crashlog), but that didn't seem to fix anything.

[First crash on Forge 47.2.0](https://github.com/NFINIT-Labs/Fantasy-Skies/files/13848895/crash-2024-01-06_18.11.46-server.txt)
[Second crash on Forge 47.2.19](https://github.com/NFINIT-Labs/Fantasy-Skies/files/13848894/crash-2024-01-06_19.32.06-server.txt)

**Comment by meglazero** [comment]
This is a botania issue that they say has a fix in the pipeline, likely won't be fixed until botania is updated: [link to botania github issue](https://github.com/VazkiiMods/Botania/issues/4527)

**Comment by knoxhack** [comment]
Fixed in 1.4.0
