### ISSUE TITLE
Enhancement: Clicking on "leaf items" in the quest book, opens JEI and shows the recipe

### ISSUE THREAD

**Issue by Astrobirder** [NFINIT-Labs/Fantasy-Skies#4]
Not sure if this is easy to do, but it would be nice, when going through the quest book and you come to a block or item that needs to be made to complete the quest to click and see the recipe--JEI is one way, but there are other solutions that would provide the info.  

Just a "Nice to have".

**Comment by knoxhack** [comment]
Implemented in 1.3.x
