### ISSUE TITLE
Primal Magick Grimoire non craftable

### ISSUE THREAD

**Issue by Psyvana** [NFINIT-Labs/Fantasy-Skies#52]
Hi there, loving the pack.

Unfortunately, the grimoire item doesn't have a recipe and it is a quest requirement.

Thanks :)

Edit: Disregard, as there was no info in the quest about crafting the grimoire, i really should have checked a mod spotlight. 
Solution: Place bookshelf down, aim at bookshelf with mundane wand in hand and hold right click until it transforms :)

**Comment by TopFox** [comment]
@Psyvana How did you charge the wand? Holding right click next to it doesn't do anything right now
