### ISSUE TITLE
Compacting Drawers crash the game v1.1.8.1

### ISSUE THREAD

**Issue by meglazero** [NFINIT-Labs/Fantasy-Skies#8]
I had this issue on a prior version, I believe it was version 1.1.6 also, but any time I put anything that should work into a compacting drawer the entire game crashes back to the launcher. Drawer is not attached to a controller, but it was doing it both attached and not attached in prior version. Has happened with gold and iron previously, and just did it with diamonds and mystical relic fragments. Crash report is linked.

[crash-2023-12-18_21.26.54-client.txt](https://github.com/NFINIT-Labs/Fantasy-Skies/files/13710821/crash-2023-12-18_21.26.54-client.txt)

**Comment by Speedy7524** [comment]
Same

**Comment by meglazero** [comment]
As of v 1.3.1 compacting drawers appear to be working again, just worked with iron ingot/nugget
